### ISSUE TITLE
Text config json file

### ISSUE THREAD

**Issue by Natsushiro** [OpenGVLab/EgoVideo#14]
Thank you for your work.
I am trying to use the backbone of your model but encountered difficulties in loading the text encoder.
For the get_text_model() method, you give:
```
def get_text_model():
    num_frames = 4
    config = edict(model)
    ####text
    text_config = edict(TextEncoders[text_enc])
    text_config_json = '/mnt/petrelfs/peibaoqi/AVION/models/pbq_umt/bert/config.json'
```
However, the json file cannot be correctly located. Could you kindly offer a config file for the text encoder?
Thank you very much.

**Comment by chaitanya100100** [comment]
@Natsushiro Did you find a solution to this?

**Comment by Natsushiro** [comment]
> @Natsushiro Did you find a solution to this?

This config file is located in ~/Egovideo/backbone/model/bert/config.json
